### ISSUE TITLE
how to use with postgresql

### ISSUE THREAD

**Issue by sarglase** [starfishs/sql2struct#24]
when i use with this command :sql2struct --dsn="postgresql://postgres:1234@127.0.0.1:5432/icp" -o ./models

it report an error: error occur sql: unknown driver "postgresql" (forgotten import?)

i dontknow  where i should  install this driver

**Comment by starfishs** [comment]
driver name is "postgres" rather than "postgresql"

The hint is not friendly enough, I will improve it
